VERBOSE_OUTPUT = False
THETA_ALLOWED_VARIANCE = 0.5
GESTURE_THRESHOLD = 0.6
START_DISTANCE_MOVEMENT = 40
ITERATIONS_AFTER_START = 35
LAST_FOUR_THRESHOLD = 145
MAXVAL_THRESHOLD = 130
MAX_TRACEPOINTS = 10
